### ISSUE TITLE
Legal Action!!!

### ISSUE THREAD

**Issue by J4awesome** [CigarProject/Cigar#110]
@m-byte @vram4 
Ok all I need to know is let's say I wanted to make a website that can sell people agar.io servers I was thinking about this Agar.io server.Would I need to add anything to the terms and agreements.Also would you be ok with this.And finally why Cigar get to host it on anyone website and Ogar has to host on Agar.io website.

**Comment by vram4** [comment]
@J4awesome Its not against the license of Ogar to do sell servers, so this would be perfectly fine. Cigar comes with a client (it used to) so people use that instead of the agario website An ogar server would work with the cigar client too, but it wouldnt be able to take advantages of the special features cigar has, ex: chat.
