### ISSUE TITLE
[question] Why do u use buffer ?

### ISSUE THREAD

**Issue by muxahuk** [CigarProject/Cigar#117]
How and why did u choosed to use buffers to transmit data to server ?
Does it gains some performance, security ?
or how did u decided to use buffers ?

**Comment by muxahuk** [comment]
found it, it's becouse of `ws` module

**Comment by muxahuk** [comment]
Learned more about `ws` module. Still same question: why did u choose to use buffers ? why not use socket.io for data transporting ?

**Comment by m-byte** [comment]
Using dataviews and buffers, only a minimal representation of the data can be sent. For example, when sending the ID of a node, we only need 4 bytes (32 bits) to represent a number that could be up to 8 characters (or bytes) long when represented as hexadecimal string or up to 10 characters when represented as decimal string.
There are other overheads associated with using strings. There would need to be some kind of separator. Often when sending text data using websockets, it is encoded as JSON. In JSON, there is not only separators, but even more additional data. All this data not only has to be sent over the network (causing somewhere along the lines of 3 times the traffic compared to the binary data), but it also has to be decoded by the receiver.
For the binary version, the computer already knows where the information it needs is stored and can more or less instantly access it. For the JSON version, it would have to go through all the characters sent, parse them, then parse part of the reconstructed data again.

socket.io is not directly related to this. It is just another abstraction layer built on top of ws. You could also send text using regular ws or binary data using socket.io. The main advantage socket.io has is the added code for fallback on browsers without websocket support. Since Cigar uses other things like canvas that are only supported on more recent browsers, the fallback is not needed.

In a way, you either write your code for computers or for humans. If you write it for humans, it is easier for humans to understand while a computer will have to do a lot more work to follow the instructions. When writing programs for computers, it is simply the other way around :wink:

**Comment by muxahuk** [comment]
ok, so it's becouse of performance.
May be you could reccomend some topics, video lessons atc. where i could learn more about buffers in browsers, in node and how is data stored, handled atc. ? if no - u can close these issue.
Thanks.

**Comment by muxahuk** [comment]
ok. Anothere question, i think related to these:
Why don't u store images in to db as buffers ? gridFS in mongo.

**Comment by MastaCoder** [comment]
@m-byte is really busy to answer :(
