### ISSUE TITLE
Friends not able to connect!

### ISSUE THREAD

**Issue by CalvinDKHD** [CigarProject/Cigar#236]
Hello, i portfowarded 88, 1501 and 1600 as i need to do, they can connect to the home screen *where is says play* but not to the game itself. it just says connecting. I portfowarded them all as TCP/UDP.

**Comment by peteracs** [comment]
I had the same issue. I realized the problem was that the client is set to connect to 127.0.0.1
I tell you how to fix this issue :
[main_out.zip](https://github.com/CigarProject/Cigar/files/252573/main_out.zip)

I attached a file. 
Put it to the client folder. Overwrite it. 
Then open it and edit 
 `    var CONNECTION_URL = "127.0.0.1";
	var OWN_IP = "127.0.0.1";`

This to your server IP

**Comment by Lukkez** [comment]
Thanks, i'll use this on my koding.io server
