### ISSUE TITLE
Adding Minions/Bots to server.

### ISSUE THREAD

**Issue by CalvinDKHD** [CigarProject/Cigar#302]
I have made this issue before, no one seemed to answer. I just wanted to do it again.

So anyone know how to do this? like in the console. Because OgarUnlimited has them and they work perfectly.
I would pay someone too make them.

**Comment by mayed505** [comment]
@CalvinDKHD how much your paying?

**Comment by CalvinDKHD** [comment]
Umm, i dont know yet. Contact me over skype and we can make a deal -
calvin.leonhardt

**Comment by CalvinDKHD** [comment]
Mayed, i will not sell them. Its for personal use.

**Comment by MastaCoder** [comment]
I am not adding this because it's pretty useless. If you really want to add it then simply get it from Ogar-Unlimited. Honestly to me Ogar-Unlimited is very poorly coded and everything is just all over the place without having any efficiency on the server. Cigar is supposed to be made for servers running 24/7, not mini private servers for users just to play on.

**Comment by CalvinDKHD** [comment]
I tried to add it from UL but i get errors.

**Comment by MastaCoder** [comment]
> Honestly to me Ogar-Unlimited is very poorly coded and everything is just all over the place without having any efficiency on the server.

**Comment by FlexibleSwift** [comment]
I'll try to add bots to cigar
