### ISSUE TITLE
The community wants Updates

### ISSUE THREAD

**Issue by RelTakeover** [CigarProject/Cigar#318]
Hello cigarProject , 
we all know that all  have occupations , but all want updates..

they could add :+1: 
- MINIMAP
- ANTI SPAM CHAT
- VISIBLE TIMER FOR AUTORESTART
- MINIONS ( MORE FUNNY )
- Improve stability splits
- Welcome message

ADD YOUR IDEA..

**Comment by FlexibleSwift** [comment]
more admin privileges

**Comment by MastaCoder** [comment]
- MINIONS ( MORE FUNNY )

never ever. Everything else, sure.

**Comment by J4awesome** [comment]
Hi,
I used to have a cigar server here and havn't really looked at this repo since last year.To everybody who has a server agar.io has died out.Slither.io is the new agar.io and mostly everyone who was working on a agar.io server is working on a slitherio server.Here is a best built server to date.
https://github.com/sitano/slitherss

**Comment by dfiverr** [comment]
Updates would be good, some sort of documentation or comments on the code would be a lot better

**Comment by MastaCoder** [comment]
Cigar is now client only.
