### ISSUE TITLE
Add a plugin slot, if you do I'll make plugins for it minions, op... things like that

### ISSUE THREAD

**Issue by ImHyper** [CigarProject/Cigar#359]

**Comment by ZfsrGhS953** [comment]
Did you even read Ogar Unlimited's contributing notice? Here's what it says:
## Contributing
Just make a pull request or make your own copy.

### Things that I don't want you to copy *(copying it to your own file or fork)*
1. No-Lag antibot measures
2. OP
3. Minions
4. Smart bot/despawn
5. Easy verify
6. Periodic things *(pmsg, pcmd, etc..)*
7. Mousefilter
8. Plugins
9. Advanced multiverse system
10. Client config system
11. Language support system
12. Tutorial system
13. Quadrants

**Anything else, if you improved it, you don't have to give us credit. Or else, if you just copied, you must give us credit**

So, if you just copy (COPY, not implement! I have my own implementation of minions in my own fork without giving credit, and AJS-development doesn't complain), you will almost certainly get a ban on AJS-development, and probably more.

**Comment by agariotips** [comment]
@ZfsrGhS953 Do you have skype?

**Comment by ImHyper** [comment]
@ZfsrGhS953 Why do you want it?

**Comment by MastaCoder** [comment]
@ZfsrGhS953 That whole text section is complete bullshit.

They are running under the Apache 2 license, they are **forced** to run under since Ogar isn't their work and they forked from Ogar which had the license.

Apache 2 strictly states that you can reproduce work for commercial, private, distributed use as much as you want, while you credit the author(s) that have worked on it.

So, if you just copy (COPY, not implement! I have my own implementation of minions in my own fork without giving credit, and AJS-development doesn't complain), you will almost certainly get a ban on AJS-development, and probably more.
