### ISSUE TITLE
Why client only?

### ISSUE THREAD

**Issue by dfiverr** [CigarProject/Cigar#384]
Why is it client only now?

**Comment by ZfsrGhS953** [comment]
Because the server was really outdated by today's standards, such as no smooth splitting, no quadtrees (that means a lot of lag), server sends useless information about cells above and below the screen (more bandwidth usage, more lag (because it doesn't have quadtrees, it checks all the cells it sends to the player) and unfair advantage for zoomhack users), cells going out of bounds when big, ejected mass going through spawners and more outdated stuff.

**Comment by deniskrop** [comment]
What is the best server implementation to use with it now? Ogar?

**Comment by dfiverr** [comment]
@ZfsrGhS953 What is the best server implementation to use with it now? Ogar?

**Comment by HAlexTM** [comment]
[MultiOgar](https://github.com/Barbosik/MultiOgar)

**Comment by ZfsrGhS953** [comment]
[MultiOgar Edited](https://github.com/Megabyte918/MultiOgar-Edited)

**Comment by Niall7459** [comment]
GET IN NICE WORK!!!

**Comment by Niall7459** [comment]
ITS AMAXING

**Comment by HAlexTM** [comment]
@Niall7459 Stop it until you have a right motivation to do so

**Comment by Niall7459** [comment]
? i am sorry

**Comment by HAlexTM** [comment]
@Niall7459 what are you doing is called spam

**Comment by Niall7459** [comment]
but this is amazing
i can create a network of agar servers!

**Comment by MastaCoder** [comment]
Yeah exactly as @ZfsrGhS953. It's pretty useless to add MultiOgar to Cigar since you can just download it at it's own repo.
