### ISSUE TITLE
Skins uploaders sucks in windows (doesnt work)

### ISSUE THREAD

**Issue by CineXMike** [CigarProject/Cigar#42]
Cant upload skins

**Comment by matrixreal** [comment]
me too got 88.167.14.2/?uploaderr=unknown
88.167.14.2 is my hosted server (my ip)

**Comment by ElMay0r** [comment]
mines don't work neither

**Comment by m-byte** [comment]
@CineXMike The windows server is not really maintained. I compiled it because there were apparently many people interested in it, but it is in no way a good solution. It is pretty buggy at the moment and I am thinking about taking the exe down. Could you try installing node.js and Visual Studio (e.g. 2010 Express).

**Comment by CineXMike** [comment]
i am not runing exe
I run master server and then use commands in nodejs

**Comment by Lukkez** [comment]
Work only put the png with no "ABC" the server suppor only "abc"

**Comment by MastaCoder** [comment]
Is this still an issue..?

**Comment by MastaCoder** [comment]
Skin uploader should be running under a web server that can run PHP.
