### ISSUE TITLE
how to =

### ISSUE THREAD

**Issue by PsycoYT** [CigarProject/Cigar#460]
how to change the appearance of a virus

**Comment by MastaCoder** [comment]
https://github.com/CigarProject/Cigar/blob/master/www/assets/js/main_out.js#L1238-L1241 - Number of points for a virus.

https://github.com/CigarProject/Cigar/blob/master/www/assets/js/main_out.js#L1322 - Where most renders can be changed.

A virus uses the isVirus variable. So if an object has that it's due to the flag sent from the server that it's a virus, thus it'll form a virus.

Nothing much is done on the server other than drawing the points, because the color is set on the server. So for further changes you'll need to add them, there isn't "much to change" :)

**Comment by PsycoYT** [comment]
thx
