### ISSUE TITLE
Client...

### ISSUE THREAD

**Issue by Mr-BrockLee** [CigarProject/Cigar#546]
Ok so I made my server and all but i dont like the main page. Where do u get these styles (Agarup.us, Ogario.gq) and Mgar.io etc Pls tell me how I can make it like that. thank You

**Comment by MastaCoder** [comment]
http://lmgtfy.com/?iie=1&q=How+to+program+HTML+and+CSS

**Comment by Mr-BrockLee** [comment]
Wow I thought u were actually gonna help, but If i make it the skins wont show, what do I do?

**Comment by Mr-BrockLee** [comment]
@MastaCoder

**Comment by Y4ssine** [comment]
you can use bootstrap it's ez to play with  if you want to edit page style
etc...   getbootstrap.com

2017-03-18 1:09 GMT+04:00 Mr-BrockLee <notifications@github.com>:

**Comment by MastaCoder** [comment]
You can't run a website if you don't know the very basics of HTML and CSS. I'm not going to spoon feed every single bit of code to you guys and expect others to do the work.

It took me literally 2 days to learn the basics because I put effort in it. You're never gonna learn if you don't put in effort into learning from what you already have. The issue already had far more than enough information in it to be able to do it, so I suggest you just keep trying until it works.
