### ISSUE TITLE
what variables was replaced in the lukas fork?^

### ISSUE THREAD

**Issue by gyeyoqu** [CigarProject/Cigar#556]
hm really need a wiki

**Comment by MastaCoder** [comment]
Cigar Code: https://github.com/CigarProject/Cigar/blob/master/www/assets/js/main_out.js
Luka Code: https://github.com/Luka967/Cigar/blob/master/www/assets/js/main_out.js

Nobody is gonna spend time to write down all the changes because it's a waste of time. Go through the files and find every change that you want.
