### ISSUE TITLE
Question about server

### ISSUE THREAD

**Issue by jinsong04** [CigarProject/Cigar#58]
@m-byte I started cigar.exe. I am having a problem saying "Not implemented" on server when i go to http://localhost:451/. Can you tell me how to solve?

**Comment by xmicro** [comment]
Well you need to have a website to hold an agar clone that supports Cigar's chat. Otherwise just use Ogar (a server that has no chat and uses agar.io itself as the client)

**Comment by m-byte** [comment]
The Client is usually started on Port 88 (It is included in Cigar)                                                                                                                                                                                                                                                                                                                                        Gesendet von meinem BlackBerry 10-Smartphone.                                                                                                                                                                                                                Von: xmicroGesendet: Donnerstag, 27. August 2015 17:12An: m-byte/CigarAntwort an: m-byte/CigarCc: m-byteBetreff: Re: [Cigar] Question about server (#58)Well you need to have a website to hold an agar clone that supports Cigar's chat. Otherwise just use Ogar (a server that has no chat and uses agar.io itself as the client)

—Reply to this email directly or view it on GitHub.

**Comment by matrixreal** [comment]
@m-byte 
thanks a lot
you are talking on webhosting right ? not home hosting ?

**Comment by m-byte** [comment]
Yes

**Comment by matrixreal** [comment]
thanks a lot i will be very happy
i'm trying to install new server / client since month with no sucess
so i'm waiting .... much appreciated thanks a lot
also we are waiting for the updates to ogar release :D

**Comment by MastaCoder** [comment]
Cigar.exe is gone.
